/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary": "#00363d",
        "outline-variant": "#3b494c",
        "secondary-fixed-dim": "#bdc2ff",
        "error-container": "#93000a",
        "primary": "#c3f5ff",
        "on-tertiary-container": "#575959",
        "surface-container-highest": "#353535",
        "tertiary-container": "#d0d0d0",
        "primary-fixed": "#9cf0ff",
        "error": "#ffb4ab",
        "on-secondary-container": "#a8afff",
        "primary-fixed-dim": "#00daf3",
        "surface-bright": "#393939",
        "inverse-on-surface": "#303030",
        "on-primary-fixed": "#001f24",
        "on-secondary-fixed": "#000767",
        "on-secondary": "#1b247f",
        "on-primary-fixed-variant": "#004f58",
        "on-background": "#e2e2e2",
        "secondary-container": "#343d96",
        "background": "#131313",
        "outline": "#849396",
        "surface-container-lowest": "#0e0e0e",
        "on-surface-variant": "#bac9cc",
        "secondary": "#bdc2ff",
        "surface-container": "#1f1f1f",
        "surface": "#131313",
        "inverse-surface": "#e2e2e2",
        "on-error-container": "#ffdad6",
        "surface-tint": "#00daf3",
        "surface-dim": "#131313",
        "inverse-primary": "#006875",
        "on-tertiary-fixed": "#1a1c1c",
        "surface-variant": "#353535",
        "on-tertiary": "#2f3131",
        "on-error": "#690005",
        "on-tertiary-fixed-variant": "#454747",
        "secondary-fixed": "#e0e0ff",
        "on-primary-container": "#00626e",
        "surface-container-high": "#2a2a2a",
        "on-secondary-fixed-variant": "#343d96",
        "on-surface": "#e2e2e2",
        "surface-container-low": "#1b1b1b",
        "tertiary": "#ececec",
        "primary-container": "#00e5ff",
        "tertiary-fixed-dim": "#c6c6c6",
        "tertiary-fixed": "#e2e2e2",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        "margin-desktop": "80px",
        "margin-mobile": "20px",
        "section-gap": "120px",
        gutter: "24px",
        "container-max": "1440px",
        unit: "8px",
      },
      fontFamily: {
        sora: ["Sora", "sans-serif"],
        manrope: ["Manrope", "sans-serif"],
        "space-grotesk": ["Space Grotesk", "sans-serif"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "0.01em", fontWeight: "400" }],
        "headline-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-xl": ["72px", { lineHeight: "80px", letterSpacing: "-0.04em", fontWeight: "800" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg-mobile": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "700" }],
      },
      animation: {
        "pulse-glow": "pulseGlow 2s ease-in-out infinite",
        "float": "float 6s ease-in-out infinite",
        "shimmer": "shimmer 2s linear infinite",
      },
      keyframes: {
        pulseGlow: {
          "0%, 100%": { boxShadow: "0 0 25px rgba(0, 229, 255, 0.4)" },
          "50%": { boxShadow: "0 0 50px rgba(0, 229, 255, 0.7)" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-20px)" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
      },
    },
  },
  plugins: [],
}
